### PR TITLE
DemoActions() fix

### PR DESCRIPTION
**Pull request by mlipok**
_WD_JsonAction() was replaced for this case should be _WD_JsonActionPointer()
I will do some other changes, please wait.

### CODE REVIEW

**Comment by mlipok** [comment]
I notice issues with `_WD_JsonActionPointer()`

I was testing wd_demo.au3 with `DemoActions()` 
Here are my results:

Before (without any _WD_JsonActionPointer ):
```JSON
{
    "actions": [{
            "id": "default mouse",
            "type": "pointer",
            "parameters": {
                "pointerType": "mouse"
            },
            "actions": [{
                    "type": "pointerMove",
                    "duration": 100,
                    "origin": {
                        "ELEMENT": "fc31606e-68a1-4513-a7e5-ed93fb573606",
                        "element-6066-11e4-a52e-4f735466cecf": "fc31606e-68a1-4513-a7e5-ed93fb573606"
                    },
                    "x": 0,
                    "y": 0
                }, {
                    "type": "pointerDown",
                    "button": 2
                }, {
                    "type": "pointerUp",
                    "button": 2
                }
            ]
        }
    ]
}
```
after using 3* _WD_JsonActionPointer() :
```JSON
{
    "actions": [{
            "id": "default mouse",
            "type": "pointer",
            "parameters": {
                "pointerType": "mouse"
            },
            "actions": [{
                    ".type": "pointerMove",
                    ".duration": 100,
                    ".origin": {
                        ".element-6066-11e4-a52e-4f735466cecf": "9c1aecbb-3d50-42d3-b7f0-336f8a5094d3"
                    },
                    ".x": 0,
                    ".y": 0
                } {
                    ".type": "pointerDown",
                    ".button": 2
                }, {
                    ".type": "pointerUp",
                    ".button": 2
                }
            ]
        }
    ]
}
```

**ISSUE 1**
keys has dots 

**ISSUE 2**
before
```JSON
                    "origin": {
                        "ELEMENT": "fc31606e-68a1-4513-a7e5-ed93fb573606",
                        "element-6066-11e4-a52e-4f735466cecf": "fc31606e-68a1-4513-a7e5-ed93fb573606"
                    },
```
now
```JSON
                    ".origin": {
                        ".element-6066-11e4-a52e-4f735466cecf": "9c1aecbb-3d50-42d3-b7f0-336f8a5094d3"
                    },
```

**Comment by Sven-Seyfert** [comment]
Oh, good point @mlipok . I thought, when it came to the changes of using Json_Put, the dots were intended by @Danp2 and okay, but I missed this obviously 🙁 .

**Review by Danp2 — CHANGES_REQUESTED** [review]
You've duplicated the "actions":[] here

**Comment by Danp2** [comment]
Not sure why you are seeing the dots. This is what I get from DemoActions after making the above corrections --

```json
{
	"actions": [
		{
			"id": "default mouse",
			"type": "pointer",
			"parameters": {
				"pointerType": "mouse"
			},
			"actions": [
				{
					"type": "pointerMove",
					"duration": 100,
					"origin": {
						"ELEMENT": "fd124790-c417-45ec-ba30-c1fa1722313a",
						"element-6066-11e4-a52e-4f735466cecf": "fd124790-c417-45ec-ba30-c1fa1722313a"
					},
					"x": 0,
					"y": 0
				},
				{
					"type": "pointerDown",
					"button": 2
				},
				{
					"type": "pointerUp",
					"button": 2
				}
			]
		}
	]
}
```

Can you check your version of JSON.au3? Mine shows `2018.12.29`

**Comment by mlipok** [comment]
> Can you check your version of JSON.au3? Mine shows `2018.12.29`

I just sent you PM in Au3Forum.

**Comment by Danp2** [comment]
FWIW, I've tested with the most recent version of the JSON UDF (currently 2021.11.20) and it worked as expected for me --

```json
{
	"actions": [
		{
			"id": "default mouse",
			"type": "pointer",
			"parameters": {
				"pointerType": "mouse"
			},
			"actions": [
				{
					"type": "pointerMove",
					"duration": 100,
					"origin": {
						"ELEMENT": "9eb361a1-4a48-4d39-af5e-624282ea2703",
						"element-6066-11e4-a52e-4f735466cecf": "9eb361a1-4a48-4d39-af5e-624282ea2703"
					},
					"x": 0,
					"y": 0
				},
				{
					"type": "pointerDown",
					"button": 2
				},
				{
					"type": "pointerUp",
					"button": 2
				}
			]
		}
	]
}
```

**Comment by mlipok** [comment]
> I've tested with the most recent version of the JSON UDF (currently 2021.11.20)

Thanks. I had (2018.12.29).

Also take a look here:
https://www.autoitscript.com/forum/topic/148114-a-non-strict-json-udf-jsmn/?do=findComment&comment=1496152

**Comment by mlipok** [comment]
@Danp2 
checked on  JSON UDF (currently 2021.11.20)  works well.

@Sven-Seyfert
Did you also have an outdated JSON UDF version?
And if so: Did updating the JSON UDF version fix the problem?

**Comment by Sven-Seyfert** [comment]
> @Danp2 checked on JSON UDF (2021.11.20) works well.
> 
> @Sven-Seyfert Did you also have an outdated JSON UDF version? And if so: Did updating the JSON UDF version fix the problem?

The curious thing is that I also use `Json.au3 (2018.12.29)` (the old version like you @mlipok) and it works like @Danp2 described/posted. I am confused 🥴 .

**Review by Danp2 — APPROVED** [review]

**Pull request merged**
