### PR TITLE
Separate _WD_JsonAction into multiple functions

### PR DESCRIPTION
**Pull request by Danp2**

### CODE REVIEW

**Review by Sven-Seyfert — APPROVED** [review]
Hi Dan,

I have some small notes but in general it looks good and should work like expected.
I didn't test it, but I strongly guess you did 😅 .

Best regards
Sven

**Comment by Danp2** [comment]
> I didn't test it, but I strongly guess you did 😅 .

Thus far I've focused my testing on _WD_JsonActionPointer with simple tests like this --

```autoit
$sJSON = _WD_JsonActionPointer('pointerDown')
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sJSON = ' & $sJSON & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
$sJSON = _WD_JsonActionPointer('pointerUp', $_WD_BUTTON_Right)
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sJSON = ' & $sJSON & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
$sJSON = _WD_JsonActionPointer('pointerMove', Default, Default, Default, Default, 'viewport')
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sJSON = ' & $sJSON & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
$sJSON = _WD_JsonActionPointer('pointerMove', Default, Default, Default, Default, 'pointer')
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sJSON = ' & $sJSON & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
$sJSON = _WD_JsonActionPointer('pointerMove', Default, Default, Default, Default, 'testing')
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sJSON = ' & $sJSON & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
```

**Comment by Danp2** [comment]
@Sven-Seyfert I think we agree on the code spacing, but you may want to review this [past discussion](https://github.com/Danp2/WebDriver/issues/120) for context.

**Review by mlipok — APPROVED** [review]
I was not able to test as so far, but....
Looks good.

**Comment by Sven-Seyfert** [comment]
> I think we agree on the code spacing, but you may want to review this past discussion for context.

- Okay, understood. To be honest I don't like the [commitment](https://github.com/Danp2/WebDriver/issues/120#issuecomment-1017997106) about "tabs", but it's also not a big deal for me.
- What I like is your last commit about the usage of Json_Put which brings a better readability and maintainance approach 👍 .

**Review by Sven-Seyfert — APPROVED** [review]
Json_Put = 🎉👍

**Pull request merged**
