### PR TITLE
Solution for 'rect' command

### PR DESCRIPTION
**Pull request by vkvtema**

### CODE REVIEW

**Comment by vkvtema** [comment]
Sorry, I looked at _WD_Window but didn’t understand what exactly needs to be changed. After all, the problem is that: `$sResult = Json_Get($oJson, "[value]")` does not return a 'rect' value.

**Comment by Danp2** [comment]
I had to take another look at the code, but I believe that both _WD_Window and _WD_ElementAction are behaving as intended. Here's an example --
```
#include "wd_core.au3"

Global $sDesiredCapabilities, $sSession, $sElement, $oWRect, $oERect

SetupChrome()
_WD_Startup()

$sSession = _WD_CreateSession($sDesiredCapabilities)
_WD_Navigate($sSession, "https://www.gmail.com")
$sElement = _WD_FindElement($sSession, $_WD_LOCATOR_ByXPath, "//input[@id='identifierId']")

$oWRect = _WD_Window($sSession, 'rect')
$oERect = _WD_ElementAction($sSession, $sElement, 'rect')

ConsoleWrite("Window Coords = " & $oWRect.Item('x') & " / " & $oWRect.Item('y') & " / " & $oWRect.Item('width') & " / " & $oWRect.Item('height') & @CRLF)
ConsoleWrite("Element Coords = " & $oERect.Item('x') & " / " & $oERect.Item('y') & " / " & $oERect.Item('width') & " / " & $oERect.Item('height') & @CRLF)

Func SetupChrome()
_WD_Option('Driver', 'chromedriver.exe')
_WD_Option('Port', 9515)
_WD_Option('DriverParams', '--verbose --log-path="' & @ScriptDir & '\chrome.log"')

$sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"goog:chromeOptions": {"w3c": true, "excludeSwitches": [ "enable-automation"], "useAutomationExtension": false }}}}'
EndFunc
```

**Comment by vkvtema** [comment]
Oh. I didn’t know about .Item('')
My mistake. Sorry

**Comment by Danp2** [comment]
No problem. I'm adding some code to wd_demo so that everyone can see how it's supposed to work.

**Pull request closed without merging**
